name : update readme on push
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: update Readme
        run: |
          echo " ### $(date)  on " ${{ github.event_name }} " BY  - " @${{ github.actor }}  >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update readme log"
          git push
      
